# Core system configuration
broker_max_workers: 4
message_retention_hours: 24
max_processing_flows: 10
flow_retention_hours: 24

# Data processing settings
staging_area:
  default_retention_days: 7
  default_quality_threshold: 0.8

# Performance and scaling
thread_pool:
  max_workers: 4
  queue_size_limit: 100